var fedanos ={
"type": "FeatureCollection",
"name": "Dano",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "05\/02\/2018", "Dia": "Lunes", "Hora": "22:15", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Shaw y Constitucion", "Lugar": "Via Publica", "Denunciant": "Giunta Brenda Camila", "Imputado": "Nn", "Sintesis": "La denunciante se encontraba en el vehiculo esperando a su pareja cuando es embestida por otro vehiculo el cual no logra ver ni asi tampoco a la persona.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8670186, -37.1109285 ] } },
{ "type": "Feature", "properties": { "Fecha": "08\/02\/2018", "Dia": "Jueves", "Hora": "06:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A2", "Calle": "Fragata Victoria 1799", "Lugar": "Domicilio Particular", "Denunciant": "Porretti Barbara", "Imputado": "Escobar Aviles Cristian Ignacio", "Sintesis": "El masculino se encontraba amenazando a la denunciante y rompiendo los vidrios de la propiedad, el mismo es aprehendido en el hecho.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8431301, -37.0924241 ] } },
{ "type": "Feature", "properties": { "Fecha": "08\/02\/2018", "Dia": "Jueves", "Hora": "11:30", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Del Tuyú 287 Pinamar", "Lugar": "Domicilio Particular", "Denunciant": "Lina Biscontin", "Imputado": "Nn", "Sintesis": "Autores ignorados violentaron el ventanal de frente, no se encontraron elementos sustraidos.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8598971, -37.1172302 ] } },
{ "type": "Feature", "properties": { "Fecha": "11\/02\/2018", "Dia": "Lunes", "Hora": "11:40", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A7", "Calle": "UADE Campus Costa Argentina", "Lugar": "Lugar Publico", "Denunciant": "Krawiec Hernesto", "Imputado": "Herrera Jonathan Ariel", "Sintesis": "El imputado habria causado damnificaciones en cinco vehiculos estacionados en la UADE el mismo es aprehendido en operativo cerrojo", "addrtype": "establishment", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.885179, -37.115962 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/02\/2018", "Dia": "Lunes", "Hora": "00:03", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Martin Pescador y Av. Del Mar", "Lugar": "Via Publica", "Denunciant": "White Eugenio Guillermo", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan el vidrio de alrededor cinco vehiculos estacionados", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8512536, -37.1125303 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/02\/2018", "Dia": "Martes", "Hora": "08:40", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Bunge 739", "Lugar": "Via Publica", "Denunciant": "Rodrigo Emanuel Nieva", "Imputado": "Barreiro Arian Jeremias", "Sintesis": "El imputado habria causado una damnificacion en un vehiculo estacionado en Mc. Donalds", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8629711, -37.113706 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/02\/2018", "Dia": "Lunes", "Hora": "19:20", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Tante Pinamar", "Lugar": "Lugar Particular", "Denunciant": "Jose Pablo De Leon", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian en dos ocasiones causado damnificaciones al restaurant del denunciante.", "addrtype": "establishment", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8570644, -37.1152915 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/02\/2018", "Dia": "Lunes", "Hora": "A establecer", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Burriquetas y Martin Pescador", "Lugar": "Via Publica", "Denunciant": "Maranghello Pablo Cesar", "Imputado": "Nn", "Sintesis": "Cuatro vehiculos se encuentran damnificados por balas efectuadas por un airecomprimido provocando roturas de puertas y vidrios.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8520202, -37.1121159 ] } },
{ "type": "Feature", "properties": { "Fecha": "13\/02\/2018", "Dia": "Martes", "Hora": "16:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A2", "Calle": "Av. Del Mar y De la Retama", "Lugar": "Via Publica", "Denunciant": "Dolezel Nicolas Ignacio", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan el vidrio del conductor del vehiculo y en el interior se encuentra un chaleco refractorio con manchas de sangre.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8386589, -37.0973309 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/02\/2018", "Dia": "Domingo", "Hora": "13:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Av. Del Mar y Eolo", "Lugar": "Via Publica", "Denunciant": "Pañalva Juan Marcelo", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan el vidrio del acompañante del vehiculo, no se constatan faltantes.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8593088, -37.1217874 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/02\/2018", "Dia": "Jueves", "Hora": "02:30", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Bunge y Jupiter", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan el cristal de un movil policial mientras personal se encontraba en pie a tierra.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8713759, -37.1115165 ] } },
{ "type": "Feature", "properties": { "Fecha": "25\/02\/2018", "Dia": "Domingo", "Hora": "23:15", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B3", "Calle": "Argel 1049", "Lugar": "Domicilio Particular", "Denunciant": "Romina Paola Elizabeth Gomez", "Imputado": "Mirta Guerra", "Sintesis": "Autores ignorados rompen postigon y ventana de la habitacions para luego rociarla con nafta  y escriben con aerosol \"La prox fuego, auto y vos\"", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8853967, -37.1346972 ] } },
{ "type": "Feature", "properties": { "Fecha": "27\/02\/2018", "Dia": "Martes", "Hora": "08:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C2", "Calle": "Spiro 1369", "Lugar": "Domicilio Particular", "Denunciant": "Perez Hector Alberto", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresaron al domicilio violentando una ventana y una puerta, no se constanta faltante alguno.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8969943, -37.1405678 ] } },
{ "type": "Feature", "properties": { "Fecha": "27\/02\/2018", "Dia": "Martes", "Hora": "13:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Martin Pescador y Verde de Circunvalacion", "Lugar": "Lugar Particular", "Denunciant": "Garde Ricardo Alfredo", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian cortado tejidos que delimitaban el terreno", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8752908, -37.0956931 ] } },
{ "type": "Feature", "properties": { "Fecha": "27\/02\/2018", "Dia": "Martes", "Hora": "13:10", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D3", "Calle": "Cerezo 342", "Lugar": "Lugar Publico", "Denunciant": "Aguilar Mauricio Leon", "Imputado": "Nn", "Sintesis": "Dos personas en moto azul intentan sustraer una ventana solo dañando los bordes con un destornillador y al ver que era observado se da a la fuga.", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9161748, -37.1634977 ] } }
]
}
