var felesiones= {
"type": "FeatureCollection",
"name": "Lesiones",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "2\/2\/2018", "Dia": "Viernes", "Hora": "17:40", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D1", "Calle": "Divisadero y Jilguero", "Lugar": "Via Publica", "Denunciant": "Serajian Lucas Daniel", "Imputado": "Sanchez Enrique", "Sintesis": "Accidente de transito entre un auto y un motovehiculo", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.899629, -37.1613746 ] } },
{ "type": "Feature", "properties": { "Fecha": "3\/2\/2018", "Dia": "Sabado", "Hora": "13:10", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Silfides y Libertador", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Kohut Daniel Alberto", "Sintesis": "Accidente de transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8701495, -37.1175894 ] } },
{ "type": "Feature", "properties": { "Fecha": "4\/2\/2018", "Dia": "Domingo", "Hora": "14:05", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B1", "Calle": "Biarritz y Estocolmo", "Lugar": "Via Publica", "Denunciant": "Pirez Juan Manuel", "Imputado": "Caceres Nicolas", "Sintesis": "Accidente de transito entre un auto y un motovehiculo", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8697896, -37.132431 ] } },
{ "type": "Feature", "properties": { "Fecha": "4\/2\/2018", "Dia": "Domingo", "Hora": "15:15", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C3", "Calle": "-56.885363, -37.142840", "Lugar": "Via Publica", "Denunciant": "Victoria Carmona", "Imputado": "Nn", "Sintesis": "Denunciante es envestida por un rodado y este se da a la fuga.", "addrtype": "locality", "addrlocat": "APPROXIMATE" }, "geometry": { "type": "Point", "coordinates": [ -56.8607055, -37.1145662 ] } },
{ "type": "Feature", "properties": { "Fecha": "8\/2\/2018", "Dia": "Jueves", "Hora": "14:16", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D1", "Calle": "Chorlo y Paraiso", "Lugar": "Via Publica", "Denunciant": "Hacha Lucio Ezequiel", "Imputado": "Ramiraez Maria Veronica", "Sintesis": "Accidente de transito entre un auto y un motovehiculo", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8940697, -37.1532197 ] } },
{ "type": "Feature", "properties": { "Fecha": "11\/2\/2018", "Dia": "Domingo", "Hora": "01:25", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C3", "Calle": "Rotonda de Valeria del Mar", "Lugar": "Via Publica", "Denunciant": "Lopez Erika Estefania", "Imputado": "Florencia Dornaletche", "Sintesis": "Confrontacion", "addrtype": "establishment", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8804016, -37.1450447 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/2\/2018", "Dia": "Lunes", "Hora": "23:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "De las Cipreses y Dunas", "Lugar": "Via Publica", "Denunciant": "Myrtis Rosita Vittone", "Imputado": "Estela Maris Franquet y Martin Alejandro Matkovich", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8687033, -37.1216049 ] } },
{ "type": "Feature", "properties": { "Fecha": "13\/2\/2018", "Dia": "Martes", "Hora": "16:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Av. Del Mar 448", "Lugar": "Via Publica", "Denunciant": "Martini Axel", "Imputado": "Castelo Natalin Solange", "Sintesis": "Accidente de Transito", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8525398, -37.1140328 ] } },
{ "type": "Feature", "properties": { "Fecha": "15\/2\/2018", "Dia": "Jueves", "Hora": "12:45", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Jason y Totoras", "Lugar": "Via Publica", "Denunciant": "Magio Omar Alfredo", "Imputado": "Ciciliano Estafania", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8727115, -37.1096901 ] } },
{ "type": "Feature", "properties": { "Fecha": "24\/2\/2018", "Dia": "Sabado", "Hora": "19:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D3", "Calle": "Acceso Carilo", "Lugar": "Via Publica", "Denunciant": "Alba Andres Nicolas y Mamani Porco Gaston", "Imputado": "Rojo Mariano Arturo", "Sintesis": "Accidente de transito entre un auto y un motovehiculo", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9239184, -37.1598031 ] } },
{ "type": "Feature", "properties": { "Fecha": "25\/2\/2018", "Dia": "Domingo", "Hora": "04:55", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Comisaria Pinamar", "Lugar": "Lugar Particular", "Denunciant": "Fernandez Eduardo Javier", "Imputado": "Gonzalez Gerardo Carlos", "Sintesis": "Confrontacion en el Calabozo", "addrtype": "establishment", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8706838, -37.111333 ] } }
]
}
