var feley23737={
"type": "FeatureCollection",
"name": "Ley23737",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "03\/02\/2018", "Dia": "Viernes", "Hora": "04:10", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C2", "Calle": "Martin de Alzaga y Espora", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Sanchez Carlos Joel Agustin", "Sintesis": "Se intercepta el vehiculo del señor Flores Burgos al ser cursado por sistema tanto el como su acompañante Sanchez no poseen impedimiento, sin embargo este tenia en su poder un tapper con 0,15 gramos de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9113467, -37.1403281 ] } },
{ "type": "Feature", "properties": { "Fecha": "03\/02\/2018", "Dia": "Sabado", "Hora": "15:30", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Balneario El Dorado Pinamar", "Lugar": "Lugar Publico", "Denunciant": "Personal Policial", "Imputado": "Somma Brian Ezequiel", "Sintesis": "1,9 grms de Marihuana", "addrtype": "bar", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.853914, -37.116034 ] } },
{ "type": "Feature", "properties": { "Fecha": "04\/02\/2018", "Dia": "Domingo", "Hora": "01:40", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C2", "Calle": "Martin de Alzaga y Espora", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Sanguinetti Roman Mario", "Sintesis": "Se intercepta el vehiculo del señor Sanguinetti  y en la bolletera del vehiculo se incauta un cigarrillo con 1,0 gr de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9113467, -37.1403281 ] } },
{ "type": "Feature", "properties": { "Fecha": "10\/02\/2018", "Dia": "Domingo", "Hora": "06:15", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Jonas y Libertador", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Garcia Jeremias Leonel", "Sintesis": "12,2 gramos de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8609446, -37.1151899 ] } },
{ "type": "Feature", "properties": { "Fecha": "10\/02\/2018", "Dia": "Sabado", "Hora": "07:00", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Totoras y Rivadavia", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Francisco Ismael Bonfranceschi y Fernandez Jose Luis", "Sintesis": "30,7 de Cocaina", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8717706, -37.1084864 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/02\/2018", "Dia": "Lunes", "Hora": "20:50", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A7", "Calle": "Tridente y Guilliver", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Meza Gonzalez Didier Jeremias", "Sintesis": "2,1 gramos de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8740853, -37.1120263 ] } },
{ "type": "Feature", "properties": { "Fecha": "19\/02\/2018", "Dia": "Lunes", "Hora": "12:26", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C2", "Calle": "Martin de Alzaga y Espora", "Lugar": "Via Publica", "Denunciant": "Gonzalez Fernandez Mauro Nicolas", "Imputado": "Nn", "Sintesis": "Se intercepta el vehiculo y en el ciudadano no recae impedimento legal sin embargo tenia 0,14 gr de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9113467, -37.1403281 ] } },
{ "type": "Feature", "properties": { "Fecha": "20\/02\/2018", "Dia": "Martes", "Hora": "21:00", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "De los Tritones 59", "Lugar": "Domicilio Particular", "Denunciant": "Personal Policial", "Imputado": "Dario Cristian Abal", "Sintesis": "4,0 gramos de Marihuana", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8595133, -37.1202994 ] } },
{ "type": "Feature", "properties": { "Fecha": "21\/02\/2018", "Dia": "Miercoles", "Hora": "04:30", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Del Mejillon 904", "Lugar": "Domicilio Particular", "Denunciant": "Personal Policial", "Imputado": "Facundo Joaquin Lacave", "Sintesis": "En allanamiento al domicilio del imputado se logra secuestrar 32 plantas de Cannabis, 7 plantas, ventiladores, lamparas, tablas de cultivo, fertilizantes y dinero en efectivo.", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8601556, -37.1111414 ] } },
{ "type": "Feature", "properties": { "Fecha": "24\/02\/2018", "Dia": "Sabado", "Hora": "09:30", "Caratula": "Ley N 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "OMBU y Divisadero", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Rafael Leandro, Cavalca Jonathan, Cavalca Leonardo", "Sintesis": "Los imputados poseian en el vehiculo 7,9grs de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9093434, -37.1731383 ] } }
]
}
