var fetrobo= {
"type": "FeatureCollection",
"name": "Trobo",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "14\/02\/2018", "Dia": "Miercoles", "Hora": "A establecer", "Caratula": "Tentativa de Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Del Pejerrey 1757", "Lugar": "Lugar Particular", "Denunciant": "Hugo Daniel Avalos", "Imputado": "Nn", "Sintesis": "Autores ignorados en horas de la madrugada violentan la reja de la ventana e intentan abrir la caja fuerte de la panderia sin lograr el objetivo.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8706486, -37.1043327 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/02\/2018", "Dia": "Domingo", "Hora": "18:15", "Caratula": "Tentativa de Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "De la Merluza  979", "Lugar": "Domicilio Particular", "Denunciant": "Arias Ures Maria Laura", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan la reja de un ventanal que se encuentra en la parte trasera de la vivienda, no se constata faltantes.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8574066, -37.1053393 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/02\/2018", "Dia": "Domingo", "Hora": "23:30", "Caratula": "Tentativa de Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C3", "Calle": "Jorge 508", "Lugar": "Domicilio Particular", "Denunciant": "Torres Diego Federico", "Imputado": "Nn", "Sintesis": "Menores en la casa empiezan a escuchar ruidos de como rompian la puerta y ventana trasera del domicilio, por lo que salen corriendo por la puerta de acceso a pedir auxilio, al llegar la policia observan a dos sujetos de sexo masculino salir corriendo.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8814266, -37.145615 ] } }
]
}
