var abdano = {
"type": "FeatureCollection",
"name": "Dano",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "20\/4\/2018", "Dia": "Viernes", "Hora": "Sin Especificar", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "De las Gaviotas 48", "Lugar": "Lugar Particular", "Denunciant": "Manasevich Nicolas", "Imputado": "Nn", "Sintesis": "Rotura de la puerta del depto. 10, no se constatan faltantes.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8587797, -37.1146539 ] } },
{ "type": "Feature", "properties": { "Fecha": "11\/4\/2018", "Dia": "Miercoles", "Hora": "Sin Especificar", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "De la ballena 99", "Lugar": "Domicilio Particular", "Denunciant": "Masso Estefania Tamara", "Imputado": "Camilo Gimenez", "Sintesis": "Autores ignarados intentan ingresar a la vivienda violentando la puerta de ingreso. No se constatan faltantes, la denunciante sospecha de el masculino \"Camilo Gimenez\"\"\"", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.857924, -37.114862 ] } },
{ "type": "Feature", "properties": { "Fecha": "26\/4\/2018", "Dia": "Jueves", "Hora": "11:00:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "De la Trucha 1882", "Lugar": "Domicilio Particular", "Denunciant": "Stringi Francisco Guillermo", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian sacado la reja de la ventana, ademas de haber corrido la misma, no se constatan faltantes", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.872374, -37.1032258 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/4\/2018", "Dia": "Jueves", "Hora": "20:30:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Carilo", "Sector": "D3", "Calle": "Paraiso 1280", "Lugar": "Domicilio Particular", "Denunciant": "Durante Ruben Oscar", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian violentado el vidrio y  forcejeado la cerradura,", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.9084189, -37.1514232 ] } },
{ "type": "Feature", "properties": { "Fecha": "14\/4\/2018", "Dia": "Viernes", "Hora": "12:40:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Valeria", "Sector": "C1", "Calle": "Espora 799", "Lugar": "Lugar Particular", "Denunciant": "Liliana Patricia Picate", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan cerradura de cuarto de electricidad para luego tironear los cables del mismo y cortarlos", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8875261, -37.1424674 ] } },
{ "type": "Feature", "properties": { "Fecha": "4\/4\/2018", "Dia": "Miercoles", "Hora": "04:40:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Victor Hugo 1832", "Lugar": "Domicilio Particular", "Denunciant": "Gallardo Miriam Edith", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian violentado una ventana del comercio", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8951843, -37.1294698 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/4\/2018", "Dia": "Domingo", "Hora": "19:30:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B2", "Calle": "Catamarca 963", "Lugar": "Domicilio Particular", "Denunciant": "Mendoza Sabino David", "Imputado": "Nn", "Sintesis": "Un vehiculo con dominio AC405BW de color blanco, eviste las cabinas de gas del domicilio y se da a la fuga.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8880818, -37.1296571 ] } },
{ "type": "Feature", "properties": { "Fecha": "5\/4\/2018", "Dia": "Jueves", "Hora": "Sin Especificar", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Urquiza 412", "Lugar": "Domicilio Particular", "Denunciant": "Miguel Angel Colsani", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian violentado la ventana en un intento de ingresar a la vivienda", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8902909, -37.1245702 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/4\/2018", "Dia": "Miercoles", "Hora": "15:50:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B1", "Calle": "Rubens y Noel", "Lugar": "Via Publica", "Denunciant": "Franco Natanael Guevara", "Imputado": "Nn", "Sintesis": "Mientras el denunciante circulaba es golpeado por un cable que habia soltado un empleado de telpin haciendo que el menor se cayera del motovehiculo", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8729147, -37.1242652 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/4\/2018", "Dia": "Domingo", "Hora": "02:15:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B1", "Calle": "Balneario Viejo Hotel", "Lugar": "Lugar Particular", "Denunciant": "Roxana Gabriela Salpeter", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian forzado el lateral de la puerta de ingreso y violentado un vidrio.", "addrtype": "establishment", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8728192, -37.136531 ] } },
{ "type": "Feature", "properties": { "Fecha": "20\/4\/2018", "Dia": "Viernes", "Hora": "21:00:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Valeria", "Sector": "C3", "Calle": "Loria 1699", "Lugar": "Domicilio Particular", "Denunciant": "Suarez Raul Alfredo", "Imputado": "Nn", "Sintesis": "Autores ignorados comienzan a tirar piedras contra la vivienda del denunciante", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8970747, -37.1486008 ] } }
]
}
