var abhurto = {
"type": "FeatureCollection",
"name": "Hurto",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "20\/4\/2018", "Dia": "Viernes", "Hora": "21:40:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Intermedanos y Cangrejo", "Lugar": "Lugar Particular", "Denunciant": "Silva Facundo Maximiliano", "Imputado": "Nn", "Sintesis": "El denunciate dejo su celular en el mostrador y al regresar el mismo le habia sido sustraido", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8752722, -37.1048827 ] } },
{ "type": "Feature", "properties": { "Fecha": "16\/4\/2018", "Dia": "Lunes", "Hora": "23:50:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Terminal De Ómnibus Pinamar", "Lugar": "Lugar Publico", "Denunciant": "Marocchini Juan Jose", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen de un colectivo estacionado una mochila con documentacion varia y 4600 pesos en efectivo perteneciente al conductor quien se ausento por cinco minutos.", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8800506, -37.1073273 ] } },
{ "type": "Feature", "properties": { "Fecha": "7\/4\/2018", "Dia": "Sabado", "Hora": "15:30:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Corvina 1033", "Lugar": "Domicilio Particular", "Denunciant": "Becerra Adrian Daniel", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan al domicilio y sustraen dos tablet, 5 mil pesos en efectivo, una mochila y prendas varias.", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8620474, -37.1082109 ] } },
{ "type": "Feature", "properties": { "Fecha": "7\/4\/2018", "Dia": "Sabado", "Hora": "21:15:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Gaviotas 447", "Lugar": "Domicilio Particular", "Denunciant": "Battistini Daniel Alejandro", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan por una ventana y sustraen una mochila con una notebook, un celular y documentacion personal", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.855592, -37.1142322 ] } },
{ "type": "Feature", "properties": { "Fecha": "28\/4\/2018", "Dia": "Sabado", "Hora": "15:39:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A2", "Calle": "De las Garzas 708", "Lugar": "Domicilio Particular", "Denunciant": "Martinez Fabian Oscar", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian roto sistema de riego y sustraido del lugar los aspersores", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8449148, -37.0929504 ] } },
{ "type": "Feature", "properties": { "Fecha": "28\/4\/2018", "Dia": "Sabado", "Hora": "22:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "De la Merluza 1213", "Lugar": "Domicilio Particular", "Denunciant": "Baraglia", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan al domicilio y sustraen una valija la cual contenia un secador de pelo, una plancha, vestimenta varia, documentacion varia y un bolso color rojo.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.858674, -37.1030826 ] } },
{ "type": "Feature", "properties": { "Fecha": "28\/4\/2018", "Dia": "Sabado", "Hora": "15:15:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "Fragata La Victoria 3725", "Lugar": "Domicilio Particular", "Denunciant": "Constanza Maria Vidal Raffo", "Imputado": "Nn", "Sintesis": "Autores ignorados sin ejercer violencia ingresan al domicilio y sustraen varios bolsas y mochilas con documentacion varia y prendas de vestir.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8372696, -37.0866198 ] } },
{ "type": "Feature", "properties": { "Fecha": "21\/4\/2018", "Dia": "Sabado", "Hora": "20:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Carilo", "Sector": "D1", "Calle": "Morera y Avestruz", "Lugar": "Domicilio Particular", "Denunciant": "Maria Paula Paterno", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan y sustraen tres celulares, vestimenta varia, una computadora, una tableta de dibujo y un disco rigido.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8910564, -37.1595632 ] } },
{ "type": "Feature", "properties": { "Fecha": "14\/4\/2018", "Dia": "Sabado", "Hora": "20:20:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Carilo", "Sector": "D2", "Calle": "Rey del Bosque y Almendro", "Lugar": "Domicilio Particular", "Denunciant": "Santamarina Ramon", "Imputado": "Nn", "Sintesis": "Autores ignorados le habrian ingresado por ventanal trasero y sustraen un televior de 42 pulgadas", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9149042, -37.1684665 ] } },
{ "type": "Feature", "properties": { "Fecha": "13\/4\/2018", "Dia": "Viernes", "Hora": "14:35:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Carilo", "Sector": "D1", "Calle": "Codorniz 343", "Lugar": "Domicilio Particular", "Denunciant": "Couco Cristina Beatriz", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen un ipod, un parlannte y dos lentes de sol del auto del denunciante", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8883417, -37.1553508 ] } },
{ "type": "Feature", "properties": { "Fecha": "30\/4\/2018", "Dia": "Lunes", "Hora": "16:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Valeria", "Sector": "C2", "Calle": "Sebastián El Cano & Tte. de Fragata Edgardo Giachino", "Lugar": "Lugar Particular", "Denunciant": "Gama Leri Gonzalo", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen del lugar dos garrafas.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9051621, -37.1370259 ] } },
{ "type": "Feature", "properties": { "Fecha": "26\/4\/2018", "Dia": "Jueves", "Hora": "Sin Especificar", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B5", "Calle": "Argel y Gaona", "Lugar": "Via Publica", "Denunciant": "Russo Walter Clemente", "Imputado": "Perez Diego Miguel", "Sintesis": "En recorrido personal policial ve un masculino reducido por un vecino tras haber sustraido pertenencias, el mismo es aprehendido y al revisarlo poseia un cuchillo profesional de 10 cm", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9030934, -37.1332863 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/4\/2018", "Dia": "Domingo", "Hora": "12:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Valeria", "Sector": "C1", "Calle": "Av. Cnel. de Marina Tomás Espora 2", "Lugar": "Via Publica", "Denunciant": "Damian Sebastian Rojo", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen del vehiculo dos celulares y documentacion varia.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8777103, -37.1461485 ] } },
{ "type": "Feature", "properties": { "Fecha": "15\/4\/2018", "Dia": "Domingo", "Hora": "21:30:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Valeria", "Sector": "C2", "Calle": "Betbeder 1909", "Lugar": "Domicilio Particular", "Denunciant": "Romero Diego", "Imputado": "Nn", "Sintesis": "Autores ignorados sin ejercer violencia ingresan al domicilio y sustraen 200.000 pesos", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.9055184, -37.1385245 ] } },
{ "type": "Feature", "properties": { "Fecha": "3\/4\/2018", "Dia": "Martes", "Hora": "07:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "San Petesburgo 1521", "Lugar": "Domicilio Particular", "Denunciant": "Arturo Leandro Santana", "Imputado": "Nn o Matias Fernandez", "Sintesis": "Autores ignorados habrian sustraido de la puerta del domicilio el motovehiculo del denunciante, el cual al poseer sospechas del imputado mencionado se dirige a su casa en Villa Gessel y encuentra la moto.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8903804, -37.1232804 ] } },
{ "type": "Feature", "properties": { "Fecha": "30\/4\/2018", "Dia": "Lunes", "Hora": "11:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B5", "Calle": "Tuyu 1069", "Lugar": "Lugar Particular", "Denunciant": "Mesia Urchoeia Estefania Solange", "Imputado": "Nn", "Sintesis": "Autores ignorados sustrean del fondo de la casa una garrafa de 10 kg", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8961552, -37.1300718 ] } },
{ "type": "Feature", "properties": { "Fecha": "30\/4\/2018", "Dia": "Lunes", "Hora": "14:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B3", "Calle": "Dakar 1239", "Lugar": "Domicilio Particular", "Denunciant": "Vegas Diego Sebastian", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan por ventana y sustraen un monitor, un teclado y mouse, el cpu y una notebook", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8875035, -37.1318679 ] } },
{ "type": "Feature", "properties": { "Fecha": "30\/4\/2018", "Dia": "Lunes", "Hora": "02:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B2", "Calle": "Praga 952", "Lugar": "Domicilio Particular", "Denunciant": "Cambre Dardo Fabian", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan por ventana y sustraen una cartera, una billetera, documentacion varia, llaves de sus vehiculos, 500 pesos en efectivo y 300 dolares.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8824494, -37.1225109 ] } },
{ "type": "Feature", "properties": { "Fecha": "11\/4\/2018", "Dia": "Miercoles", "Hora": "20:15:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Victor Hugo y Tuyu", "Lugar": "Lugar Particular", "Denunciant": "Ariel Alfredo Motarse", "Imputado": "Nicolas Leonardo Lopez", "Sintesis": "El imputado habria sustraido del supermercado un perfume y el mismo es identificado por camaras y aprehendido por la policia en Monaco y Esparza", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8960772, -37.1294038 ] } },
{ "type": "Feature", "properties": { "Fecha": "11\/4\/2018", "Dia": "Miercoles", "Hora": "22:30:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "España 464", "Lugar": "Lugar Particular", "Denunciant": "Hector Daniel Sanchez", "Imputado": "Nn", "Sintesis": "Autores ignorados previo violentar un ventiluz y sustraen 10000 pesos", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.888935, -37.1252364 ] } },
{ "type": "Feature", "properties": { "Fecha": "15\/4\/2018", "Dia": "Domingo", "Hora": "14:00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B2", "Calle": "Rotonda Ostende", "Lugar": "Transporte Publico", "Denunciant": "Alfarodoti Sofia", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen un morral con medicacion, dos tarjetas de credito y documentacion varia mientras la denunciante se encontraba dormida en el omnibus", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8784416, -37.1307749 ] } }
]
}
