var ablesiones = {
"type": "FeatureCollection",
"name": "Lesiones",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "20\/4\/2018", "Dia": "Viernes", "Hora": "19:42:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Constitucion y Apolo", "Lugar": "Via Publica", "Denunciant": "Carbone y Bonas Maria Sol", "Imputado": "Nn", "Sintesis": "Accidente de transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8738313, -37.1085491 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/4\/2018", "Dia": "Miercoles", "Hora": "13:05:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Bunge y Libertador", "Lugar": "Via Publica", "Denunciant": "Martina Garcia", "Imputado": "Azul Villalba", "Sintesis": "Confrontacion entre dos menores", "addrtype": "establishment", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8675293, -37.1115152 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/4\/2018", "Dia": "Miercoles", "Hora": "15:45:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Del Tridente y Heraclidas", "Lugar": "Via Publica", "Denunciant": "Olmedo Emiliano Luis Damian", "Imputado": "Aurora Liliana Villarreal", "Sintesis": "Accidente de transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8749409, -37.1156318 ] } },
{ "type": "Feature", "properties": { "Fecha": "7\/4\/2018", "Dia": "Sabado", "Hora": "16:00:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "El mas Alla", "Lugar": "Via Publica", "Denunciant": "Soriano Silvia Elizabeth", "Imputado": "Nn", "Sintesis": "Accidente de transito", "addrtype": "bar", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8181941, -37.0689474 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/4\/2018", "Dia": "Miercoles", "Hora": "13:20:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Jonas 952", "Lugar": "Lugar Publico", "Denunciant": "Canetti Luca", "Imputado": "Nn", "Sintesis": "Confrontacion entre menores.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8682511, -37.1126302 ] } },
{ "type": "Feature", "properties": { "Fecha": "21\/4\/2018", "Dia": "Sabado", "Hora": "21:30:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Av. Bunge y Shaw", "Lugar": "Via Publica", "Denunciant": "Miño Lidia Esther", "Imputado": "Nn", "Sintesis": "Accidente de transito", "addrtype": "establishment", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8671529, -37.1113655 ] } },
{ "type": "Feature", "properties": { "Fecha": "14\/4\/2018", "Dia": "Sabado", "Hora": "06:30:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Jupiter y Rivadavia", "Lugar": "Via Publica", "Denunciant": "Barrientos Catalina Micaela", "Imputado": "Pereyra Lautaro y Pereyra Oriana", "Sintesis": "Confrontacion", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8700745, -37.1090837 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/4\/2018", "Dia": "Jueves", "Hora": "11:20:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Jason y Totoras", "Lugar": "Via Publica", "Denunciant": "Scocco Matias Gabriel", "Imputado": "Hefner Albino Aurelio", "Sintesis": "Accidente de transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8727115, -37.1096901 ] } },
{ "type": "Feature", "properties": { "Fecha": "30\/4\/2018", "Dia": "Lunes", "Hora": "20:15:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Corvina y Juno", "Lugar": "Via Publica", "Denunciant": "Calderon Chaile Milena Mijal", "Imputado": "Tacchetti Andrea Cecilia", "Sintesis": "Accidente de transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8737995, -37.1048087 ] } },
{ "type": "Feature", "properties": { "Fecha": "26\/4\/2018", "Dia": "Jueves", "Hora": "16:30:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Escuela Corbeta Urugay", "Lugar": "Lugar Publico", "Denunciant": "Leonardo Nicolas Lopez", "Imputado": "Fausto Dos Santos", "Sintesis": "Confrontacion entre menores.", "addrtype": "establishment", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8698572, -37.1123899 ] } },
{ "type": "Feature", "properties": { "Fecha": "8\/4\/2018", "Dia": "Domingo", "Hora": "19:41:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Valeria", "Sector": "C3", "Calle": "Colon y Arcachon", "Lugar": "Via Publica", "Denunciant": "Flores Chalar Jovana Sandra", "Imputado": "Lucia Quispe Puita de Condo", "Sintesis": "Accidente de transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8977546, -37.1424198 ] } },
{ "type": "Feature", "properties": { "Fecha": "24\/4\/2018", "Dia": "Martes", "Hora": "09:30:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B5", "Calle": "Cherburgo y Andes", "Lugar": "Via Publica", "Denunciant": "Sequeira Laura Esther", "Imputado": "Vera Paredes Sasha Yamila", "Sintesis": "Confrontacion", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9003937, -37.1326085 ] } }
]
}
