var abley23737 = {
"type": "FeatureCollection",
"name": "Ley23737",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "11\/4\/2018", "Dia": "Miercoles", "Hora": "02:30:00", "Caratula": "Ley 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Martin Pescador y Shaw", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Galorla Lautaro, Tomas Mendez y Christian Walter Cabrera", "Sintesis": "4,6 gramos de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.863252, -37.1044817 ] } },
{ "type": "Feature", "properties": { "Fecha": "10\/4\/2018", "Dia": "Martes", "Hora": "20:30:00", "Caratula": "Ley 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "-37.11663, -56.85476", "Lugar": "Lugar Publico", "Denunciant": "Personal Policial", "Imputado": "Torrada Matias Nicolas y Diambrosio Mariano Miguel", "Sintesis": "0,6 gramos de Marihuana", "addrtype": "locality", "addrlocat": "APPROXIMATE" }, "geometry": { "type": "Point", "coordinates": [ -56.8607055, -37.1145662 ] } },
{ "type": "Feature", "properties": { "Fecha": "11\/4\/2018", "Dia": "Miercoles", "Hora": "02:30:00", "Caratula": "Ley 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Martin Pescador y Shaw", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Galorla Lautaro, Tomas Mendez y Christian Walter Cabrera", "Sintesis": "4,6 gramos de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.863252, -37.1044817 ] } },
{ "type": "Feature", "properties": { "Fecha": "27\/4\/2018", "Dia": "Viernes", "Hora": "02:20:00", "Caratula": "Ley 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Tridente y Av. Bunge", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Bausela Agustin y Gulo Luca Emanuel", "Sintesis": "Los imputados poseian una bolsa de nylon con Marihuana", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8732991, -37.1194627 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/4\/2018", "Dia": "Domingo", "Hora": "16:00:00", "Caratula": "Ley 23.737", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Tuyu y Central", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Leonardo Nicolas Gomez", "Sintesis": "12,2 gramos de Marihuana", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8954084, -37.1241569 ] } }
]
}
