var abrobo= {
"type": "FeatureCollection",
"name": "Robo",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "14\/4\/2018", "Dia": "Sabado", "Hora": "11:40:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "Libertador y Poseidon", "Lugar": "Via Publica", "Denunciant": "Weinzettel Adrian", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan ventan del vehiculo y sustraen una cartera y una biletera con documentacion varia.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8270511, -37.0772115 ] } },
{ "type": "Feature", "properties": { "Fecha": "9\/4\/2018", "Dia": "Lunes", "Hora": "Sin Especificar", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Terminal De Ómnibus Pinamar", "Lugar": "Lugar Publico", "Denunciant": "Garcia Raul Ariel", "Imputado": "Nn", "Sintesis": "El denunciante dejo su bicicleta con candado por dos dias y al regresar la misma habia sido sustraida", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8800506, -37.1073273 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/4\/2018", "Dia": "Domingo", "Hora": "13:40:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Carilo", "Sector": "D1", "Calle": "Hornero y Molle", "Lugar": "Domicilio Particular", "Denunciant": "Matias Mendez Casariego", "Imputado": "Nn", "Sintesis": "Autores ignorados ejercen violencia sobe ventana y sustraen una valija, dos mochilas, vestimenta varia y un celular.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8999665, -37.1567301 ] } },
{ "type": "Feature", "properties": { "Fecha": "24\/4\/2018", "Dia": "Martes", "Hora": "20:15:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Carilo", "Sector": "D1", "Calle": "Avutarda 796", "Lugar": "Domicilio Particular", "Denunciant": "Ayala Victor Hugo", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan una ventana y sustraen un televisor y un parlante.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8925445, -37.1630722 ] } },
{ "type": "Feature", "properties": { "Fecha": "8\/4\/2018", "Dia": "Domingo", "Hora": "21:00:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B2", "Calle": "Av. Central 664", "Lugar": "Domicilio Particular", "Denunciant": "Mamani Alejandra Silvia", "Imputado": "Hernandez Lucas Sebastian", "Sintesis": "El imputado habria ingresado a la vivienda y sustraido dos celulares, al darse a la fuga es reducido por la denunciante y al llegar la policia el mismo es aprehendido", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8790153, -37.12583 ] } },
{ "type": "Feature", "properties": { "Fecha": "9\/4\/2018", "Dia": "Lunes", "Hora": "05:20:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Victor Hugo 2148", "Lugar": "Domicilio Particular", "Denunciant": "Pablo Ezequiel Barrios", "Imputado": "Cabanillas Lucas Damian", "Sintesis": "El imputado previo romper puerta de ingreso sustraen mercaderia, dinero en efectivo y herramientas de trabajo", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8992457, -37.1291262 ] } },
{ "type": "Feature", "properties": { "Fecha": "30\/4\/2018", "Dia": "Lunes", "Hora": "18:30:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B5", "Calle": "Junin 1699", "Lugar": "Domicilio Particular", "Denunciant": "Fleitas Damian Alejandro", "Imputado": "Nn", "Sintesis": "Autores ignorados previo forzar ventana ingresan y sustraen un televisor, un dvd, un telefono, pañales, una moladora, una aujereadora y una cepilladora.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8994161, -37.1351005 ] } },
{ "type": "Feature", "properties": { "Fecha": "11\/4\/2018", "Dia": "Miercoles", "Hora": "18:00:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Victor Hugo 2148", "Lugar": "Lugar Particular", "Denunciant": "Rojas Facundo Martin", "Imputado": "Nn", "Sintesis": "Dos masculinos ingresan al comercio y amenazando al empleado le sustraen dos telefonos celulares aparentando portar un arma entre sus prendas, los mismos se dan a la fuga", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8992457, -37.1291262 ] } },
{ "type": "Feature", "properties": { "Fecha": "25\/4\/2018", "Dia": "Miercoles", "Hora": "20:00:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B2", "Calle": "Saavedra 981", "Lugar": "Lugar Particular", "Denunciant": "Mirma Rodriguez Socaño", "Imputado": "Nn", "Sintesis": "Un masculino ingresa al comercio y amenazando con un arma de fuego tipo revolver exige todo el dinero, sustrayendo 2000 pesos dandose  a la fuga por saavedra en direccion norte.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8855477, -37.1300456 ] } },
{ "type": "Feature", "properties": { "Fecha": "24\/4\/2018", "Dia": "Martes", "Hora": "18:30:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B1", "Calle": "Biarritz y Corso Florida", "Lugar": "Via Publica", "Denunciant": "Fleitas Norma Ester", "Imputado": "Nn", "Sintesis": "La denunciante es interceptada por un masculino el cual exhibe un cuchillo y le sustrae un celular y se da ala fuga por corso florida sentido Norte", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8679778, -37.1299515 ] } },
{ "type": "Feature", "properties": { "Fecha": "17\/4\/2018", "Dia": "Martes", "Hora": "00:00:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Victor Hugo 1999", "Lugar": "Domicilio Particular", "Denunciant": "Villasanti Zarate Vicente Aurelia", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen un motovehiculo el cual estaba estacionado bajo techo con libre acceso.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8973234, -37.1292207 ] } },
{ "type": "Feature", "properties": { "Fecha": "17\/4\/2018", "Dia": "Martes", "Hora": "04:00:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Victor Hugo 1825", "Lugar": "Domicilio Particular", "Denunciant": "Oviedo Juan Manuel", "Imputado": "Nn", "Sintesis": "Autores ignorados previo violentar puerta sustraen 4 celulares, 6000 pesos en efectivo y un parlante", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.895092, -37.1294088 ] } },
{ "type": "Feature", "properties": { "Fecha": "26\/4\/2018", "Dia": "Jueves", "Hora": "13:30:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B3", "Calle": "Cairo 1333", "Lugar": "Domicilio Particular", "Denunciant": "Alberto Rodriguez", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan al domicilio violentando e ingresando por un hueco debajo de la ventana y sustraen un televisor, una notebook, un dvd y un cargador.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8892659, -37.1352652 ] } },
{ "type": "Feature", "properties": { "Fecha": "19\/4\/2018", "Dia": "Jueves", "Hora": "15:00:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B4", "Calle": "Arcachon y Mons", "Lugar": "Domicilio Particular", "Denunciant": "Outon Julio Alberto", "Imputado": "Nn", "Sintesis": "Autores ignorados violentan las rejas de una de las habitacion y sustraen una cartera, llaves de una farmacia, llaves de un departamento, secador de pelo, un telefono inalambrico, vestimentas varias y cadenas de oro.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8944326, -37.1269007 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/4\/2018", "Dia": "Domingo", "Hora": "19:45:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B5", "Calle": "-37.13474, -56.90323", "Lugar": "Lugar Particular", "Denunciant": "Migoya Oscar Alberto", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen el vehiculo del denunciante (Ford 150) para luego lo abandonarlo en Gaona y Cairo", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -58.5285855, -34.6183987 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/4\/2018", "Dia": "Domingo", "Hora": "14:30:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Ostende", "Sector": "B2", "Calle": "-37.12475, -56.88618", "Lugar": "Via Publica", "Denunciant": "Carlos Miranda Bernal", "Imputado": "Burgos Agustin y Ridruguez Claudio Ezequiel", "Sintesis": "Mientras el denunciante circulaba a pie es interceptado por un motovehiculo con dos Nn  el cual uno de ellos le coloca un elemento contundente en la cintura exigiendo el celular , el denunciante al no tener nada encima se le sustrae la mochila, estos se", "addrtype": "convenience_store", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -58.5281882, -34.6188436 ] } }
]
}
