var mahurtos={
"type": "FeatureCollection",
"name": "Hurto",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "02\/03\/2018", "Dia": "Viernes", "Hora": "20:30", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B3", "Calle": "Av La Plata 1039", "Lugar": "Lugar Particular", "Denunciant": "Kauf Adolfo", "Imputado": "Nn", "Sintesis": "Autores ignorados le sustraen el bolso con documentacion varia y llaves del auto mientras este se retiro a buscar otro producto en el supermercado.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8783411, -37.1272917 ] } },
{ "type": "Feature", "properties": { "Fecha": "02\/03\/2018", "Dia": "Viernes", "Hora": "22:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B5", "Calle": "Ayacucho 1236", "Lugar": "Domicilio Particular", "Denunciant": "Aguirre Roberto Sebastian", "Imputado": "Nn", "Sintesis": "Autores ignorados le sustraen un televisor y una manta del domicilio", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8976866, -37.1319732 ] } },
{ "type": "Feature", "properties": { "Fecha": "02\/03\/2018", "Dia": "Viernes", "Hora": "23:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D3", "Calle": "Eucaliptus y Ñandu", "Lugar": "Domicilio Particular", "Denunciant": "Correa Andrea Fabiana", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan por puerta trasera y sustraen dos celulares, una cartera y documentacion varia.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9085781, -37.1589147 ] } },
{ "type": "Feature", "properties": { "Fecha": "05\/03\/2018", "Dia": "Lunes", "Hora": "10:23", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B4", "Calle": "San Petesburgo 1521", "Lugar": "Domicilio Particular", "Denunciant": "Edgardo Oscar Santilli", "Imputado": "Nn", "Sintesis": "Autores ignorados previo ingresar por ventan sustraen tres celulares y herramientas de trabajo varias.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8903804, -37.1232804 ] } },
{ "type": "Feature", "properties": { "Fecha": "05\/03\/2018", "Dia": "Lunes", "Hora": "21:30", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B1", "Calle": "Estocolmo 688", "Lugar": "Domicilio Particular", "Denunciant": "Mirma Vanesa Miranda", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan al domicilio y sustraen un televisor, una notebook, un parlante, una mochila con documentacion varia y 10000 pesos", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8746329, -37.129497 ] } },
{ "type": "Feature", "properties": { "Fecha": "06\/03\/2018", "Dia": "Martes", "Hora": "A establecer", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A2", "Calle": "Submarino Peral 3075", "Lugar": "Domicilio Particular", "Denunciant": "Franzatti Edgardo Oscar Santos", "Imputado": "Nn", "Sintesis": "Autores ignorados sin ejercer violencia ingresan al domicilio y sustraen 8000 dolares, 35000 pesos, Rolex, tres pistolas semi automaticas, una carabina semiautomatica, una escopeta, un revolver, escopeta de dos cañones.", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8436715, -37.0905024 ] } },
{ "type": "Feature", "properties": { "Fecha": "07\/03\/2018", "Dia": "Miercoles", "Hora": "11:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Divisadero 1224", "Lugar": "Domicilio Particular", "Denunciant": "Stonelli Ricardo", "Imputado": "Nn", "Sintesis": "Autores ignorados sin ejercer violencia ingresan y sustraen un celular, un reloj, alajas varias y un bolso de playa", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.9037983, -37.1655271 ] } },
{ "type": "Feature", "properties": { "Fecha": "10\/03\/2018", "Dia": "Sabado", "Hora": "20:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D1", "Calle": "Codorniz 147", "Lugar": "Domicilio Particular", "Denunciant": "Azzolini Enrique Ruben", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan sin ejercer violencia y sustraen un celular, dos notebook, mochila y dinero en efectivo a constatar.", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8877319, -37.1546062 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/03\/2018", "Dia": "Lunes", "Hora": "14:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B5", "Calle": "Canada 2061", "Lugar": "Domicilio Particular", "Denunciant": "Gayoso Analia", "Imputado": "Nn", "Sintesis": "Autores ignorados previo ingresar por una ventana sin ejercer violencia sustraen 400 dolares y 30000 pesos.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8984588, -37.1318814 ] } },
{ "type": "Feature", "properties": { "Fecha": "13\/03\/2018", "Dia": "Martes", "Hora": "00:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "Artemisa 261", "Lugar": "Domicilio Particular", "Denunciant": "Maria Cristina Fuentes", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan por ventanal del comedor y sustraen una notebook, una tablet, televisor 32 pulgadas, un reproductor de musica, 1500 pesos y billetera con documentacion varia.", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8339243, -37.0803486 ] } },
{ "type": "Feature", "properties": { "Fecha": "16\/03\/2018", "Dia": "Viernes", "Hora": "A establecer", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Del Libertador y Bunge", "Lugar": "Domicilio Particular", "Denunciant": "Cassels Roberto Keith", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan por puerta trasera y sustraen una mochila, un ipad y un iphone", "addrtype": "establishment", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8675293, -37.1115152 ] } },
{ "type": "Feature", "properties": { "Fecha": "17\/03\/2018", "Dia": "Sabado", "Hora": "18:10", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B5", "Calle": "Dakar y Ayacucho", "Lugar": "Domicilio Particular", "Denunciant": "Luciana Ayelen Rodriguez", "Imputado": "Romina Rojas", "Sintesis": "Dejo la bicicleta en la vivienda de la amiga la cual ahora se niega de devolversela.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8975503, -37.1310829 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/03\/2018", "Dia": "Domingo", "Hora": "13:30", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Besugo 1006", "Lugar": "Domicilio Particular", "Denunciant": "Lagos Mabel Beatriz", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan sin ejercer violencia y sustraen un celular y 9000 pesos", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8593818, -37.1058636 ] } },
{ "type": "Feature", "properties": { "Fecha": "23\/03\/2018", "Dia": "Viernes", "Hora": "07:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Cangrejo 1866", "Lugar": "Via Publica", "Denunciant": "Perez Caro Carla", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen una moto y un casco estacionada en la vereda del denunciante", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8736101, -37.1056037 ] } },
{ "type": "Feature", "properties": { "Fecha": "27\/03\/2018", "Dia": "Martes", "Hora": "09:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Lenguado 1648", "Lugar": "Via Publica", "Denunciant": "Araujo Cristian Javier", "Imputado": "Nn", "Sintesis": "Autores ignorados sustraen un vehiculo estacionado en la vereda, el mismo posee seguro contra robos.", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8692697, -37.1057586 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/03\/2018", "Dia": "Jueves", "Hora": "20:15", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Chaja y Araucaria", "Lugar": "Domicilio Particular", "Denunciant": "Panario Guillermo Francisco", "Imputado": "Nn", "Sintesis": "Autores ignorados sin ejercer violencia ingresan por la ventana y sustraen dos celulares, y dinero en efectivo a constatar.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9068642, -37.1686096 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/03\/2018", "Dia": "Jueves", "Hora": "A establecer", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "De las Dunas 364", "Lugar": "Domicilio Particular", "Denunciant": "Fernando Andres Doreman", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian ingresado al domicilio y sustraido del comedor un iphone", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8607578, -37.1211688 ] } },
{ "type": "Feature", "properties": { "Fecha": "31\/03\/2018", "Dia": "Sabado", "Hora": "21:00", "Caratula": "Hurto", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D3", "Calle": "Montero 460", "Lugar": "Domicilio Particular", "Denunciant": "Elias Daniel Antonio", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian ingresado por puerta trasera y sustraen dos notebooks", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9082801, -37.1556822 ] } }
]
}
