var malesiones={
"type": "FeatureCollection",
"name": "Lesiones",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "02\/03\/2018", "Dia": "Viernes", "Hora": "01:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B1", "Calle": "Madero y Estrasburgo", "Lugar": "Via Publica", "Denunciant": "Personal Policial", "Imputado": "Martini Axel Demian y Toriano Jazmin Daiana", "Sintesis": "Los dos imputados estaban en un terreno y al llegar personal policial intentan darse a la fuga, una vez aprehendidos comienzan a confrontar al personal.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8736283, -37.1326854 ] } },
{ "type": "Feature", "properties": { "Fecha": "05\/03\/2018", "Dia": "Lunes", "Hora": "22:43", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B5", "Calle": "Canada y Arcachon", "Lugar": "Via Publica", "Denunciant": "Gonzalez Mari Teresa", "Imputado": "Nn", "Sintesis": "Confrontacion", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8951216, -37.1321522 ] } },
{ "type": "Feature", "properties": { "Fecha": "09\/03\/2018", "Dia": "Viernes", "Hora": "11:45", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B2", "Calle": "Dante y Repetto", "Lugar": "Via Publica", "Denunciant": "Hernan Vera Ayala", "Imputado": "Maria Isabel Amengual", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8875265, -37.1282872 ] } },
{ "type": "Feature", "properties": { "Fecha": "09\/03\/2018", "Dia": "Viernes", "Hora": "16:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Cazon y Valle Fertil", "Lugar": "Via Publica", "Denunciant": "Fernandez Tomas Owen", "Imputado": "Folgoso Francisco", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8643602, -37.1104524 ] } },
{ "type": "Feature", "properties": { "Fecha": "17\/03\/2018", "Dia": "Sabado", "Hora": "21:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Martin Pescador y Shaw", "Lugar": "Via Publica", "Denunciant": "Virgilio Marian Lina", "Imputado": "Nn", "Sintesis": "Confrontacion", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.863252, -37.1044817 ] } },
{ "type": "Feature", "properties": { "Fecha": "18\/03\/2018", "Dia": "Domingo", "Hora": "09:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B4", "Calle": "Victor Hugo y Anspach", "Lugar": "Lugar Particular", "Denunciant": "Aldana Villa Pedro", "Imputado": "Nn", "Sintesis": "Confrontacion", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8962652, -37.1293806 ] } },
{ "type": "Feature", "properties": { "Fecha": "25\/03\/2018", "Dia": "Domingo", "Hora": "23:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Eneas y Del Cazon", "Lugar": "Via Publica", "Denunciant": "Godoy Aristides Jose", "Imputado": "Daniel Forment", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.868013, -37.1090393 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/03\/2018", "Dia": "Jueves", "Hora": "00:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Valle Fertil y Constitucion", "Lugar": "Via Publica", "Denunciant": "Micaela Agustina Carrizo", "Imputado": "Marchetti Sebastian", "Sintesis": "Accidente de Transito", "addrtype": "cafe", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.864627, -37.111714 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/03\/2018", "Dia": "Jueves", "Hora": "18:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "-56.87384, -37.11132", "Lugar": "Via Publica", "Denunciant": "Federico Matias Gonzalez Beniuc", "Imputado": "Magariños Ramiro Jesus", "Sintesis": "Accidente de Transito", "addrtype": "establishment", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.87384, -37.11132 ] } },
{ "type": "Feature", "properties": { "Fecha": "30\/03\/2018", "Dia": "Viernes", "Hora": "A establecer", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "El Más Allá", "Lugar": "Via Publica", "Denunciant": "Murguia Elida Noemi", "Imputado": "Fernandez Fernando Gabriel", "Sintesis": "Accidente de Transito", "addrtype": "bar", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8181941, -37.0689474 ] } }
]
}
