var marobos={
"type": "FeatureCollection",
"name": "Robo",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "08\/03\/2018", "Dia": "Jueves", "Hora": "07:55", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B4", "Calle": "Victor Hugo y Loria", "Lugar": "Domicilio Particular", "Denunciant": "Mamani Patricia Alejandra", "Imputado": "Nn", "Sintesis": "Autores ignorados previo romper el candado de la puerta de ingreso sustraen un bolso con vestimenta varia y 3000 pesos.", "": null, "1": null, "addrtype": null, "addrlocat": "intersection" }, "geometry": { "type": "Point", "coordinates": [ -56.8934975, -37.129606 ] } },
{ "type": "Feature", "properties": { "Fecha": "08\/03\/2018", "Dia": "Jueves", "Hora": "18:30", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B4", "Calle": "Ostende Tuyu 484", "Lugar": "Domicilio Particular", "Denunciant": "Cardozo Sergio Ariel", "Imputado": "Nn", "Sintesis": "Autores ignorados previo dañar la ventana del domicilio sustraen 8000 pesos y un telefono", "": null, "1": null, "addrtype": null, "addrlocat": "street_address" }, "geometry": { "type": "Point", "coordinates": [ -56.8953928, -37.124051 ] } },
{ "type": "Feature", "properties": { "Fecha": "13\/03\/2018", "Dia": "Martes", "Hora": "01:20", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Del Odiseo", "Lugar": "Domicilio Particular", "Denunciant": "Miranda Vicente Ernesto", "Imputado": "Nn", "Sintesis": "Autores ignorados ingresan forzando ventana trasera y sustraen un televisor 50 pulgadas.", "": null, "1": null, "addrtype": null, "addrlocat": "route" }, "geometry": { "type": "Point", "coordinates": [ -56.8667432, -37.1212858 ] } },
{ "type": "Feature", "properties": { "Fecha": "15\/03\/2018", "Dia": "Jueves", "Hora": "10:30", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C2", "Calle": "Alzaga 65", "Lugar": "Domicilio Particular", "Denunciant": "Giammatteo Jose Ramon", "Imputado": "Nn", "Sintesis": "Autores ignorados previo forzar una ventana sustraen una netbook y 40000 pesos.", "": null, "1": null, "addrtype": null, "addrlocat": "street_address" }, "geometry": { "type": "Point", "coordinates": [ -56.908885, -37.1348676 ] } },
{ "type": "Feature", "properties": { "Fecha": "16\/03\/2018", "Dia": "Viernes", "Hora": "20:30", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D1", "Calle": "Chorlo 704", "Lugar": "Domicilio Particular", "Denunciant": "Muñoz Manuel Javier", "Imputado": "Nn", "Sintesis": "Autores ignorados previo forzar y romper la puerta ingresan y sustraen un ipod, guitarra electrica ibanez y una mochila.", "": null, "1": null, "addrtype": null, "addrlocat": "route" }, "geometry": { "type": "Point", "coordinates": [ -56.8946651, -37.1549693 ] } },
{ "type": "Feature", "properties": { "Fecha": "21\/03\/2018", "Dia": "Miercoles", "Hora": "01:00", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A5", "Calle": "Pejerrey 1693", "Lugar": "Domicilio Particular", "Denunciant": "Ponce Jenuano", "Imputado": "Arias Porteño", "Sintesis": "El señor Arias \"Porteño\" es inquilino del denunciante quien le sustrae del pantalon tras frocejear la suma de 3300 pesos.", "": null, "1": null, "addrtype": null, "addrlocat": "street_address" }, "geometry": { "type": "Point", "coordinates": [ -56.8695414, -37.1047098 ] } },
{ "type": "Feature", "properties": { "Fecha": "25\/03\/2018", "Dia": "Domingo", "Hora": "21:30", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D1", "Calle": "Molle 912", "Lugar": "Domicilio Particular", "Denunciant": "Poppi Nahuel Alfredo", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian ingresado previo romper puerta trasera y sustraen una notebook, dinero en efectivo a constatar y documentacion varia.", "": null, "1": null, "addrtype": null, "addrlocat": "route" }, "geometry": { "type": "Point", "coordinates": [ -56.8972385, -37.1569835 ] } },
{ "type": "Feature", "properties": { "Fecha": "25\/03\/2018", "Dia": "Domingo", "Hora": "A establecer", "Caratula": "Robo", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "C2", "Calle": "-56.89682, -37.13531", "Lugar": "Domicilio Particular", "Denunciant": "Personal Policial", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian violentado la ventana del domicilio y sustraido un televisor.", "": null, "1": null, "addrtype": null, "addrlocat": "locality" }, "geometry": { "type": "Point", "coordinates": [ -56.89682, -37.13531 ] } }
]
}
