var endanos= {
"type": "FeatureCollection",
"name": "Danos",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "07\/01\/2018", "Dia": "Domingo", "Hora": "02:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Simbad el Marino y Eolo", "Lugar": "Via Publica", "Denunciant": "Tizio Mayer Ricardo Victor", "Imputado": "Nn", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8637527, -37.1188756 ] } },
{ "type": "Feature", "properties": { "Fecha": "09\/01\/2018", "Dia": "Martes", "Hora": "22:30", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Fabrica de Cerveza", "Lugar": "Via Publica", "Denunciant": "Tardivo Liliana Estela", "Imputado": "Nn", "Sintesis": "Autores ignorados dañan el ventilete del lado del acompañante delantero.", "addrtype": "bar", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.859878, -37.117048 ] } },
{ "type": "Feature", "properties": { "Fecha": "09\/01\/2018", "Dia": "Martes", "Hora": "20:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Cerezo y Divisadero", "Lugar": "Via Publica", "Denunciant": "Faccipieri Guillarme Edmundo", "Imputado": "Nn", "Sintesis": "Autores ignorados dañan ventanilla delantera del lado de conductor.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9031352, -37.1641333 ] } },
{ "type": "Feature", "properties": { "Fecha": "09\/01\/2018", "Dia": "Martes", "Hora": "21:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Avellano y Divisadero", "Lugar": "Via Publica", "Denunciant": "Garibaldi Paola Elizabeth", "Imputado": "Nn", "Sintesis": "Autores ignorados habian dañado el ventilete del lado del conductor no se constatan faltantes.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9047536, -37.1669637 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/01\/2018", "Dia": "Lunes", "Hora": "Sin especificar", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Simbad el Marino 148", "Lugar": "Domicilio Particular", "Denunciant": "Gallo Tagle Marcelo Luis", "Imputado": "Nn", "Sintesis": "Autores ignorados ejercen violencia sobre postigos que traban la puerta y el marco de la ventana al activarse la alarma se dan a la fuga.", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.8621258, -37.1132639 ] } },
{ "type": "Feature", "properties": { "Fecha": "23\/01\/2018", "Dia": "Martes", "Hora": "10:42", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B1", "Calle": "Defensa 474", "Lugar": "Domicilio Particular", "Denunciant": "Alberto de Gasperin", "Imputado": "Nn", "Sintesis": "Autores ignorados rompen una reja hacia el fondo de su vivienda.", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8715611, -37.1302902 ] } },
{ "type": "Feature", "properties": { "Fecha": "25\/01\/2018", "Dia": "Jueves", "Hora": "21:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Del Mejillon 691", "Lugar": "Domicilio Particular", "Denunciant": "Larumbe Arauje Mariana", "Imputado": "Nn", "Sintesis": "Autores ignorados habrian violentado la reja de la parte trasera de la vivienda, no se registran faltantes.", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8601556, -37.1111414 ] } },
{ "type": "Feature", "properties": { "Fecha": "25\/01\/2018", "Dia": "Jueves", "Hora": "04:00", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Av. Del Mar 656", "Lugar": "Domicilio Particular", "Denunciant": "Marco Stefani", "Imputado": "Nn", "Sintesis": "Momentos de la madrugada escuchan como patean la puerta con intenciones de entrar a la vivienda, al llegar la policia los autores no se encontraban.", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.8497841, -37.1106395 ] } },
{ "type": "Feature", "properties": { "Fecha": "26\/01\/2018", "Dia": "Viernes", "Hora": "Sin especificar", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Bunge y De las Sirenas", "Lugar": "Via Publica", "Denunciant": "Mattei Lucas Agustin", "Imputado": "Nn", "Sintesis": "Autores ignorados rompen el cristal trasero del vehiculo.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8569024, -37.115903 ] } },
{ "type": "Feature", "properties": { "Fecha": "28\/01\/2018", "Dia": "Domingo", "Hora": "07:09", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B1", "Calle": "Almirante Brown 74", "Lugar": "Domicilio Particular", "Denunciant": "Joaquin Cordoba", "Imputado": "Nn", "Sintesis": "Un grupo de aproximadamente doce y trece personas comienzan a golpear a el denunciante y sus amigos rompiendo ventanas, sillas, muebles.", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8654965, -37.1244615 ] } },
{ "type": "Feature", "properties": { "Fecha": "30\/01\/2018", "Dia": "Martes", "Hora": "04:45", "Caratula": "Damnificacion", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Avellano y Boyero", "Lugar": "Lugar Particular", "Denunciant": "Personal Policial", "Imputado": "Nn", "Sintesis": "En patrullaje escuchan un ruido y al dirigirse al lugar de donde provino constatan un daño en el local, no se constatan faltantes.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9035446, -37.167104 ] } }
]
}
