var enlesiones={
"type": "FeatureCollection",
"name": "Lesiones",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Fecha": "03\/01\/2018", "Dia": "Miercoles", "Hora": "15:03", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D1", "Calle": "Paraiso y Hornero", "Lugar": "Via Publica", "Denunciant": "Gaston Messias", "Imputado": "Alvaro Ignacio Lopez", "Sintesis": "Colision entra una moto y un auto", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8978847, -37.1516964 ] } },
{ "type": "Feature", "properties": { "Fecha": "06\/01\/2018", "Dia": "Sabado", "Hora": "Sin especificar", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "El Más Allá", "Lugar": "Via Publica", "Denunciant": "Vallero Lucas", "Imputado": "Bidondo Nestor Ulises", "Sintesis": "Accidente de Transito", "addrtype": "bar", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8181941, -37.0689474 ] } },
{ "type": "Feature", "properties": { "Fecha": "12\/01\/2018", "Dia": "Viernes", "Hora": "13:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Goleta Independencia y Shaw", "Lugar": "Via Publica", "Denunciant": "Gonzalez Nestor Fabian", "Imputado": "Fechero Laura Graciela", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8536002, -37.0993784 ] } },
{ "type": "Feature", "properties": { "Fecha": "15\/01\/2018", "Dia": "Lunes", "Hora": "22:40", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Casuarina y Perdiz", "Lugar": "Lugar Publico", "Denunciant": "Falcon Carlos Daniel", "Imputado": "Eduardo Solano", "Sintesis": "El masculino Eduardo Solano agrede fiscamente dejando inconciente al denunciante.", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.9112968, -37.1645966 ] } },
{ "type": "Feature", "properties": { "Fecha": "15\/01\/2018", "Dia": "Lunes", "Hora": "15:40", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "El Más Allá", "Lugar": "Lugar Publico", "Denunciant": "Jonatan Lee", "Imputado": "Hoyeghgwco Lee", "Sintesis": "Accidente de Transito", "addrtype": "bar", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8181941, -37.0689474 ] } },
{ "type": "Feature", "properties": { "Fecha": "15\/01\/2018", "Dia": "Lunes", "Hora": "19:50", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "El Más Allá", "Lugar": "Lugar Publico", "Denunciant": "Martin Ivan", "Imputado": "Herrara Agustin", "Sintesis": "Accidente de Transito", "addrtype": "bar", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8181941, -37.0689474 ] } },
{ "type": "Feature", "properties": { "Fecha": "16\/01\/2018", "Dia": "Martes", "Hora": "22:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Valle Fertil y Rivadavia", "Lugar": "Via Publica", "Denunciant": "Christian Ricardo Fuentes", "Imputado": "Alcorta Clara Maria", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8643742, -37.1107646 ] } },
{ "type": "Feature", "properties": { "Fecha": "20\/01\/2018", "Dia": "Sabado", "Hora": "20:30", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A1", "Calle": "Elios y Libertador", "Lugar": "Via Publica", "Denunciant": "Milo Terramagra, Pereyra Paula", "Imputado": "Fariña Agustin Alberto", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8265201, -37.0763601 ] } },
{ "type": "Feature", "properties": { "Fecha": "21\/01\/2018", "Dia": "Domingo", "Hora": "Sin especificar", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A6", "Calle": "Bunge 999", "Lugar": "Lugar Publico", "Denunciant": "Lucas Hernan Puig", "Imputado": "Nn", "Sintesis": "Confrontacion", "addrtype": "street_address", "addrlocat": "ROOFTOP" }, "geometry": { "type": "Point", "coordinates": [ -56.865629, -37.112562 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/01\/2018", "Dia": "Lunes", "Hora": "Sin especificar", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A4", "Calle": "Av. Del Mar y De Los Tirremes", "Lugar": "Via Publica", "Denunciant": "Frias Florencia", "Imputado": "Stark Julieta", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8452712, -37.1056229 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/01\/2018", "Dia": "Lunes", "Hora": "09:14", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B2", "Calle": "Victor Hugo y Pichincha", "Lugar": "Via Publica", "Denunciant": "Tisera Franco", "Imputado": "Contreras Muñoz Juan", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8801769, -37.1307254 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/01\/2018", "Dia": "Lunes", "Hora": "20:50", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B2", "Calle": "-56.889558, -37.129886", "Lugar": "Via Publica", "Denunciant": "Mariana Veronica Lombera", "Imputado": "Nn", "Sintesis": "Accidente de transito, el auto se da a la fuga.", "addrtype": "establishment", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.860495, -37.113271 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/01\/2018", "Dia": "Lunes", "Hora": "12:55", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B1", "Calle": "BARTOLOME Mitre", "Lugar": "Domicilio Particular", "Denunciant": "Nadia Magali De la Calle", "Imputado": "Nn", "Sintesis": "Confrontacion", "addrtype": "route", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8637934, -37.1264122 ] } },
{ "type": "Feature", "properties": { "Fecha": "22\/01\/2018", "Dia": "Lunes", "Hora": "Sin especificar", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Acacia y Benteveo", "Lugar": "Via Publica", "Denunciant": "Juan Cruz Ascua", "Imputado": "Brest Guido Martin", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8998799, -37.1741917 ] } },
{ "type": "Feature", "properties": { "Fecha": "23\/01\/2018", "Dia": "Martes", "Hora": "06:00", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Simbad el Marino y Del Odiseo", "Lugar": "Lugar Publico", "Denunciant": "Jeremias Anderson", "Imputado": "Nn", "Sintesis": "Confrontacion", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8626975, -37.121004 ] } },
{ "type": "Feature", "properties": { "Fecha": "23\/01\/2018", "Dia": "Martes", "Hora": "Sin especificar", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Mar y Quintana", "Lugar": "Lugar Publico", "Denunciant": "Fowler Dapremon", "Imputado": "De Lucca Francisco Javier y Bordobello Timoteo", "Sintesis": "Confrontacion", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8626397, -37.1229515 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/01\/2018", "Dia": "Lunes", "Hora": "00:48", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "B2", "Calle": "Av. Central y Matheu", "Lugar": "Domicilio Particular", "Denunciant": "Alfredo Andres Rios", "Imputado": "Montenegro Mariano", "Sintesis": "Confrontacion", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8807099, -37.1250058 ] } },
{ "type": "Feature", "properties": { "Fecha": "29\/01\/2018", "Dia": "Lunes", "Hora": "Sin especificar", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "D2", "Calle": "Castaño 274", "Lugar": "Lugar Particular", "Denunciant": "Gabriela Laura Leonelli Linale", "Imputado": "Estafania Soledad Funes", "Sintesis": "Confrontacion", "addrtype": "street_address", "addrlocat": "RANGE_INTERPOLATED" }, "geometry": { "type": "Point", "coordinates": [ -56.9045854, -37.1658053 ] } },
{ "type": "Feature", "properties": { "Fecha": "31\/01\/2018", "Dia": "Miercoles", "Hora": "18:50", "Caratula": "Lesiones", "Pais": "Argentina", "Provincia": "Buenos Aires", "Localidad": "Pinamar", "Sector": "A8", "Calle": "Jonas y Libertador", "Lugar": "Via Publica", "Denunciant": "Pablo Vicente Enriquez", "Imputado": "Nogueira Nicolas Martin", "Sintesis": "Accidente de Transito", "addrtype": "intersection", "addrlocat": "GEOMETRIC_CENTER" }, "geometry": { "type": "Point", "coordinates": [ -56.8609446, -37.1151899 ] } }
]
}
